import type {LucideIcon} from "lucide-react-native";
import {
    BookOpen,
    Bookmark,
    BookmarkCheck,
    ChartNoAxesCombined,
    Check,
    CircleAlert,
    CircleCheck,
    CircleGauge,
    CircleX,
    Clock,
    Flame,
    Highlighter,
    History,
    House,
    Info,
    Lightbulb,
    LockKeyhole,
    Menu,
    MessageSquareText,
    PencilLine,
    RotateCcw,
    Settings,
    SkipForward,
    Target,
    WholeWord,
    X,
} from "lucide-react-native/icons";

export const iconRegistry = {
    accuracy: CircleGauge,
    check: Check,
    clear: RotateCcw,
    close: X,
    error: CircleX,
    goal: Target,
    hint: Lightbulb,
    home: House,
    info: Info,
    library: BookOpen,
    lock: LockKeyhole,
    mistake: Highlighter,
    practice: PencilLine,
    progress: ChartNoAxesCombined,
    menu: Menu,
    review: History,
    save: Bookmark,
    saved: BookmarkCheck,
    sentence: MessageSquareText,
    settings: Settings,
    skip: SkipForward,
    streak: Flame,
    success: CircleCheck,
    time: Clock,
    warning: CircleAlert,
    word: WholeWord,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
